openapi: 3.0.0
info:
  title: Medicine Management API
  description: 의약품 관리 및 사용자 인증 API
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: 개발 서버

paths:
  /auth/register:
    post:
      tags:
        - 인증
      summary: 회원가입
      description: 새로운 사용자를 등록합니다. 프로필 이미지 업로드를 포함할 수 있습니다.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - email
                - password
                - name
              properties:
                email:
                  type: string
                  format: email
                  description: 사용자 이메일 주소
                  example: user@example.com
                password:
                  type: string
                  format: password
                  description: 사용자 비밀번호 (최소 6자 이상)
                  example: "password123"
                name:
                  type: string
                  description: 사용자 이름
                  example: "홍길동"

      responses:
        "201":
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "회원가입이 완료되었습니다."
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        example: "550e8400-e29b-41d4-a716-446655440000"
                      email:
                        type: string
                        example: "user@example.com"
                      name:
                        type: string
                        example: "홍길동"
                      profile_img_url:
                        type: string
                        example: "http://localhost:8000/upload/profile_123456.jpg"
        "400":
          description: 잘못된 요청
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "이메일과 비밀번호는 필수 입력값입니다."
        "409":
          description: 이메일 중복
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "이미 존재하는 이메일입니다."
        "500":
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "서버 에러가 발생했습니다."

  /auth/login:
    post:
      tags:
        - 인증
      summary: 로그인
      description: 사용자 로그인
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  msg:
                    type: string
        "500":
          description: 로그인 실패

  /myPage/post_myMedi:
    post:
      tags:
        - 마이페이지
      summary: 나의 약품 등록
      description: 새로운 약품 정보 등록
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mediName:
                  type: string
                companyName:
                  type: string
                buyingDate:
                  type: string
                  format: date
                expDate:
                  type: string
                  format: date
                mainSymptom:
                  type: string
                memo:
                  type: string
                user_id:
                  type: string
                notification:
                  type: boolean
      responses:
        "201":
          description: 약품 등록 성공
        "400":
          description: 잘못된 요청
        "500":
          description: 서버 에러

  /myPage/get_myMediList/{user_id}:
    get:
      summary: 나의 약품 목록 조회
      description: 사용자의 등록된 약품 목록을 조회합니다
      tags:
        - 마이페이지
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
          description: 사용자 ID
      responses:
        "200":
          description: 약품 목록 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    medicine_id:
                      type: string
                    medi_name:
                      type: string
                    company_name:
                      type: string
                    buying_date:
                      type: string
                      format: date
                    exp_date:
                      type: string
                      format: date
                    main_symptom:
                      type: string
                    memo:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    notification:
                      type: boolean
                    user_email:
                      type: string
        "500":
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

  /myPage/delete_myMediList/{medicine_id}:
    delete:
      summary: 약품 삭제
      tags:
        - 마이페이지
      description: 등록된 약품을 삭제합니다
      parameters:
        - in: path
          name: medicine_id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 약품 삭제 성공
        "404":
          description: 약품을 찾을 수 없음
        "500":
          description: 서버 에러

  /myPage/update_myMedi/{medicine_id}:
    put:
      tags:
        - 마이페이지
      summary: 나의 약품 정보 수정
      description: 등록된 약품 정보를 수정합니다
      parameters:
        - in: path
          name: medicine_id
          required: true
          schema:
            type: string
          description: 약품 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mediName:
                  type: string
                companyName:
                  type: string
                buyingDate:
                  type: string
                  format: date
                expDate:
                  type: string
                  format: date
                mainSymptom:
                  type: string
                memo:
                  type: string
                notification:
                  type: boolean
      responses:
        "200":
          description: 약품 정보 수정 성공
        "400":
          description: 잘못된 요청
        "404":
          description: 약품을 찾을 수 없음
        "500":
          description: 서버 에러

  /email/send-email:
    post:
      tags:
        - 이메일
      summary: 이메일 전송
      description: 알림 이메일 전송
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                subject:
                  type: string
                text:
                  type: string
      responses:
        "200":
          description: 이메일 전송 성공
        "500":
          description: 서버 에러

  /medicine/info:
    get:
      tags:
        - 의약품 정보
      summary: 전체 의약품 정보 조회
      description: 데이터베이스에 저장된 모든 의약품 정보를 조회합니다
      responses:
        '200':
          description: 의약품 정보 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: 의약품 고유 ID
                    효능:
                      type: string
                      description: 의약품의 효능 정보
                    주요증상:
                      type: string
                      description: 의약품이 대응하는 주요 증상
        '500':
          description: 서버 에러
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "서버 오류가 발생했습니다."
                  error:
                    type: string
                    description: 상세 에러 메시지

components:
  schemas:
    Error:
      type: object
      properties:
        msg:
          type: string
          description: 에러 메시지

tags:
  - name: 인증
    description: 회원가입/로그인 관련 API
  - name: 마이페이지
    description: 약품 관리 관련 API
  - name: 이메일
    description: 이메일 알림 관련 API
  - name: 의약품 정보
    description: 의약품 정보 조회 및 검색 관련 API
